backend:
  name: github
  repo: olethomas93/vuepressCMS
  branch: master # Branch to update (optional; defaults to master)
media_folder: "src/.vuepress/public/images"
public_folder: "src/.vuepress/dist/"
collections:
  - name: "doc" # Used in routes, e.g., /admin/collections/blog
    label: "Doc" # Used in the UI
    label_singular: 'Docs'
    folder: "src" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    nested:
      depth: 1000
      summary: '{{title}}'
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }